name: Run Lighthouse CI on Cron

on:
  pull_request:
    types: [closed]
  # schedule:
  #   - cron: "40 5 * * *" # KST 오후 2시 40분 (UTC 오전 5시 40분)
  # workflow_dispatch:

jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      # - name: Build
      #   run: yarn build

      - name: run Lighthouse CI
        run: |
          npm install && npm install -g @lhci/cli
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Run Lighthouse Report Script
        run: node ./scripts/lighthouse-report.js
