name: Run Lighthouse CI on Pull Request Merge

on:
  pull_request:
    types: [closed]

jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install Packages
        run: npm install && npm install -g @lhci/cli@0.14.x

      - name: Build
        run: yarn build

      - name: Run Lighthouse CI and Save Report
        run: lhci autorun --outputPath=./lhci-reports
        continue-on-error: true

      - name: Upload Lighthouse Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: lighthouse-report
          path: ./lhci-reports/*

      - name: Post Lighthouse CI Result to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPORT_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"body": "Lighthouse CI Report is available [here]('"$REPORT_URL"')."}' \
            "${{ github.api_url }}/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
