name: Run Lighthouse CI on Pull Request Merge

on:
  pull_request:
    types: [closed]

jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install Packages
        run: npm install && npm install -g @lhci/cli@0.14.x

      - name: Build
        run: yarn build

      - name: Autorun
        run: lhci autorun

      - name: Upload
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: lhci upload
